version: "3.8"

services:
  db:
    image: postgres:alpine3.16
    context: ./db
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - pgvolume:/var/lib/postgresql/data

volumes:
  pgvolume:
